Glioblastoma example notebook
AllenInstitute/open_dataset_tools pull request #3
Opened 2021-05-10 20:21 UTC by njmei

This PR is intended to address:
https://github.com/AllenInstitute/AllenSDK/issues/1648

2021-05-11 16:47 UTC, danielsf requested changes
What is the rationale for having the utility functions (`section_image_loader`, `section_metadata_cached_loader`, `section_image_dowloader`) defined in the notebook, rather than in a module that the notebook imports?

If we put the functions in a module then people who (like me) prefer working in scripts to working in notebooks can import the functions from their own scripts. I suspect this would be especially useful for someone who wants to start a job downloading the whole dataset and walk away from it while it runs.

I'm open to arguments why the notebook should remain as-is, but that is my opinion.

2021-05-11 16:58 UTC, djkapner commented
I added come ReviewNB comments.
Why are these files in the root of this repo?

2021-05-11 17:49 UTC, danielsf approved these changes
Based on our conversation after stand up, this is ready to merge.

2021-05-11 20:56 UTC, njmei commented
@djkapner Okay, I think I've addressed most of your comments. Let me know if anything else stands out.

2021-05-11 21:13 UTC, djkapner approved these changes

2021-05-11 21:24 UTC, merged

2021-05-12 15:15 UTC, wbwakeman reviewed
submitting these now.  Maybe they were not seen before?

2021-05-12 15:15 UTC, wbwakeman commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "- Companion clinical database hosted at https://ivygap.swedish.org (registration required)\n",
URL should be: https://ivygap.org/

2021-05-12 15:15 UTC, wbwakeman commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "The image data for the project is being made available as an Amazon Web Services (AWS) public dataset to enable computational scientists easy access to a rich, well-annotated data set for traini
I'm still pretty confused by what access people should expect.  I don't think this console link works for non-admins, even if they are logged in with their AWS account.  Probably should remove that URL.  The S3 ARN should stay though.

2021-05-12 15:15 UTC, wbwakeman commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "- Each donor can have one or more (tumor tissue) specimens\n",
I like this clear description.  One addition:
"Each donor (a human cancer patient) can have one or more (tumor tissue) specimens"

2021-05-12 15:15 UTC, wbwakeman commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "The section metadata table includes information about sliced tissues sections obtained from specimens including primer sequence data used for in situ hybridization experiments.\n",
sliced tissues sections -> sliced tissue sections

2021-05-12 15:15 UTC, wbwakeman commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "For the purposes of this demo notebook, it is sufficient to know that one can use matplotlib plot some previews of `Image` objects:"
use matplotlib plot -> use matplotlib to plot

2021-05-12 15:15 UTC, wbwakeman commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "section_image_table = section_image_loader(\n",
Oh man. I got a "MemoryError" while it was downloading the 10th image of the set. Not sure if there is anything to be done about it.  Unfortunately, it does prevent me from going forward with the notebook

2021-05-12 17:21 UTC, njmei commented on Programmatic_access_of_Ivy_Glioblastoma_Atlas_Project_data.ipynb
> +    "section_image_table = section_image_loader(\n",
How much RAM does the system you tried this on have?