[WIP] Repository refactor
AllenInstitute/open_dataset_tools pull request #4
Opened 2021-06-13 21:03 UTC by njmei

This PR encompasses work to improve the usability and formatting of utilities and example notebooks for accessing AWS open datasets for the Allen Mouse Brain Atlas and Ivy Glioblastoma Atlas Project.

Improvements:
- The Ivy GAP example notebook should no longer cause crashes (please test this out if you have time @wbwakeman)
- The Allen Mouse Brain Atlas utils and example notebook no longer needs credentials to access data significantly simplifying access

NOTE:
I've run out of steam for this weekend and will likely need to continue this effort next weekend. This is a good point to get feedback though

TODO:
- [ ] Need to fix existing tests for Allen Mouse Brain Atlas utils, they're currently all failing
- [ ] (maybe ?) Need to get rid of all `os.path` stuff in favor of `pathlib.Path`
- [ ] (maybe ?) Need to add tests for new Ivy GAP utils
- [ ] Need to update main repo readme

2021-06-14 16:25 UTC, wbwakeman commented
I think the URL of the "companion clinical database" still needs to be updated to: https://ivygap.org/
(At least that is the URL that seems to work now - https://ivygap.swedish.org/ does not - seems like that changed????)

2021-06-14 17:19 UTC, wbwakeman commented
GBM notebook downloads primary, annotation, boundary images but doesn't display them - is that expected?

![image](https://user-images.githubusercontent.com/1855315/121932710-07d19c80-ccfa-11eb-9d8f-a5e97fc8de6a.png)

2021-06-21 15:14 UTC, wbwakeman commented
Cool.  Yes, I see the images now. Thanks @njmei

2021-06-21 15:14 UTC, wbwakeman approved these changes

2021-06-22 05:38 UTC, danielsf requested changes
I think something got changed in the Allen Brain Atlas utils. If I run the notebook, the first image (around cell 19) looks like this
<img width="752" alt="first_coronal_image" src="https://user-images.githubusercontent.com/1682854/122869363-021f1c80-d2e1-11eb-913c-82abdde43625.png">
If I go back to the state of the repository before this branch, I do not see that large chunk of black at the bottom. Selecting other levels of downsampling for this sub image also results in black bars at different places in the image.

I'm not sure how that is even possible, given that the code claims to verify the MD5 checksum of the image on download.

This doesn't implicate the IVY blastoma code. If we want to merge this PR and take a new ticket to fix the ABA part of the repository (which, after all, is technically my problem), I am okay with that decision (@wbwakeman )

2021-06-22 05:38 UTC, danielsf commented on src/open_dataset_tools/ivy_gap_utils.py
> +class ImagePromise(object):
Do you mind adding a short docstring, in case someone else has to maintain this, so we know what this class is for?

2021-06-22 05:38 UTC, danielsf commented on src/open_dataset_tools/ivy_gap_utils.py
> +            if local_save_directory is None:
Do you need this if/else block? Doesn't `ImagePromise.__init__` default to `local_save_directory=None` (which, I think is the only difference between `if` and `else`?

2021-06-22 06:13 UTC, njmei commented
@danielsf That is very bizarre... when I ran the notebook, the images looked normal:

https://github.com/AllenInstitute/open_dataset_tools/blob/repository-refactor/example_notebooks/Accessing_Allen_Mouse_Brain_Atlas_Data.ipynb

Though maybe there is a boto3 related download problem? I *did* end up needing to set: `ImageFile.LOAD_TRUNCATED_IMAGES = True` (See: https://pillow.readthedocs.io/en/stable/reference/ImageFile.html#PIL.ImageFile.LOAD_TRUNCATED_IMAGES)

2021-06-22 15:36 UTC, danielsf commented
@njmei I tried the notebook again this morning. The problem went away. Given the way we keep talking about this repository, I assume we don't want to invest the time in trying to figure out what happened last night. I'll approve the PR and we can wait to see if anyone else encounters this problem....?

2021-06-22 15:37 UTC, danielsf approved these changes
There were a few small in-line comments. Nothing major.

2021-06-22 18:13 UTC, wbwakeman commented on src/open_dataset_tools/ivy_gap_utils.py
> +class ImagePromise(object):
Images look okay for me when I run that

2021-06-29 03:32 UTC, merged